version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: scrollify_pg
    restart: always
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: scrollifyvsas
      POSTGRES_DB: scrollify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
